theme: jekyll-theme-slate
url: "https://spatineo.github.io/ry-tietomallit/" # the base hostname & protocol for your site
home: "https://spatineo.github.io/ry-tietomallit/"
repository: spatineo/ry-tietomallit
name: "RY-tietomallit - Spatineo"
name_short: "RY-tietomallit - Spatineo"
beta: true
#google_analytics: G-TL17CQFMFK
accessibility_statement_url: "/accessibility_statement.html"
plugins:
- jekyll-sitemap
- kramdown


